import type { ShippingSession } from "./shipping-service";

export const demoShippingSessions: ShippingSession[] = [
    {
        id: "DEV-SHP-001",
        warehouseId: "dev-warehouse-north",
        destination: "DEV Магазин Химки",
        destinationType: "store",
        destinationId: "dev-store-khimki",
        status: "picking",
        createdAt: "2026-03-10T09:15:00.000Z",
        requestNumber: "DEV-REQ-OPEN-01",
        invoiceNumber: "DEV-SHP-FILE-001.xlsx",
        supplier: "DEV Менеджер",
        type: "file",
        items: [
            {
                id: "DEV-SHP-001-ITEM-1",
                originalName: "Маршрутизатор MikroTik",
                sku: "DEV-RTR-01",
                productId: "demo-product-dev-rtr-01",
                quantity: 1,
                expectedQuantity: 1,
                scannedQuantity: 1,
                scans: [
                    {
                        id: "DEV-SHP-001-SCAN-1",
                        timestamp: 1773134100000,
                        quantity: 1,
                        isManual: false,
                        code: "DEV-SN-0003",
                    },
                ],
            },
            {
                id: "DEV-SHP-001-ITEM-2",
                originalName: "POS-терминал WinLab",
                sku: "DEV-POS-01",
                productId: "demo-product-dev-pos-01",
                quantity: 1,
                expectedQuantity: 1,
                scannedQuantity: 0,
                scans: [],
            },
        ],
    },
    {
        id: "DEV-SHP-002",
        warehouseId: "dev-warehouse-north",
        destination: "DEV Магазин Атриум",
        destinationType: "store",
        destinationId: "dev-store-atrium",
        status: "shipped",
        createdAt: "2026-03-09T11:40:00.000Z",
        completedAt: "2026-03-09T13:10:00.000Z",
        requestNumber: "DEV-REQ-SUP-02",
        invoiceNumber: "DEV-SHP-FILE-002.xlsx",
        supplier: "DEV Поддержка",
        type: "file",
        items: [
            {
                id: "DEV-SHP-002-ITEM-1",
                originalName: "Сканер штрихкода Honeywell",
                sku: "DEV-SCAN-01",
                productId: "demo-product-dev-scan-01",
                quantity: 1,
                expectedQuantity: 1,
                scannedQuantity: 1,
                scans: [
                    {
                        id: "DEV-SHP-002-SCAN-1",
                        timestamp: 1773048600000,
                        quantity: 1,
                        isManual: false,
                        code: "DEV-SN-0008",
                    },
                ],
            },
            {
                id: "DEV-SHP-002-ITEM-2",
                originalName: "Этикетки 58x40",
                sku: "DEV-LABEL-01",
                productId: "demo-product-dev-label-01",
                quantity: 3,
                expectedQuantity: 3,
                scannedQuantity: 3,
                scans: [
                    {
                        id: "DEV-SHP-002-SCAN-2",
                        timestamp: 1773048720000,
                        quantity: 3,
                        isManual: true,
                    },
                ],
            },
        ],
    },
    {
        id: "DEV-SHP-003",
        warehouseId: "dev-warehouse-south",
        destination: "DEV Склад Север",
        destinationType: "warehouse",
        destinationId: "dev-warehouse-north",
        status: "draft",
        createdAt: "2026-03-11T08:25:00.000Z",
        invoiceNumber: "DEV-MOVE-001",
        supplier: "DEV Кладовщик",
        type: "manual",
        linkedReceivingId: "dev-receiving-draft",
        items: [
            {
                id: "DEV-SHP-003-ITEM-1",
                originalName: "Точка WiFi Ubiquiti",
                sku: "DEV-WIFI-01",
                productId: "demo-product-dev-wifi-01",
                quantity: 0,
                expectedQuantity: 0,
                scannedQuantity: 0,
                scans: [],
            },
        ],
    },
];
